package common.lang;

import org.tartarus.snowball.Among;

/**
 * This class was automatically generated by a Snowball to Java compiler
 * It implements the stemming algorithm defined by a snowball script.
 */
public class CzechStemmer extends org.tartarus.snowball.SnowballProgram {

	private static final long serialVersionUID = 1L;
	private final static CzechStemmer methodObject = new CzechStemmer();
	private final static Among a_0[] = {
		new Among("", -1, 16, "", methodObject),
		new Among("\u00E1", 0, 1, "", methodObject),
		new Among("\u00E9", 0, 2, "", methodObject),
		new Among("\u00ED", 0, 3, "", methodObject),
		new Among("\u00F3", 0, 4, "", methodObject),
		new Among("\u00FA", 0, 5, "", methodObject),
		new Among("\u00FD", 0, 6, "", methodObject),
		new Among("\u010D", 0, 7, "", methodObject),
		new Among("\u010F", 0, 8, "", methodObject),
		new Among("\u011B", 0, 9, "", methodObject),
		new Among("\u0148", 0, 10, "", methodObject),
		new Among("\u0159", 0, 11, "", methodObject),
		new Among("\u0161", 0, 12, "", methodObject),
		new Among("\u0165", 0, 13, "", methodObject),
		new Among("\u016F", 0, 14, "", methodObject),
		new Among("\u017E", 0, 15, "", methodObject)
	};
	private final static Among a_1[] = {
		new Among("bude", -1, 1, "", methodObject),
		new Among("budeme", 0, 1, "", methodObject),
		new Among("budete", 0, 1, "", methodObject),
		new Among("bude\u0161", 0, 1, "", methodObject),
		new Among("budou", -1, 1, "", methodObject),
		new Among("budu", -1, 1, "", methodObject),
		new Among("bu\u010F", -1, 1, "", methodObject),
		new Among("bu\u010Fme", 6, 1, "", methodObject),
		new Among("bu\u010Fte", 6, 1, "", methodObject),
		new Among("byl", -1, 1, "", methodObject),
		new Among("chce", -1, 8, "", methodObject),
		new Among("chceme", 10, 8, "", methodObject),
		new Among("chcete", 10, 8, "", methodObject),
		new Among("chce\u0161", 10, 8, "", methodObject),
		new Among("chci", -1, 8, "", methodObject),
		new Among("cht\u00EDc", -1, 8, "", methodObject),
		new Among("cht\u00EDce", 15, 8, "", methodObject),
		new Among("cht\u011B", -1, 8, "", methodObject),
		new Among("cht\u011Bj", 17, 8, "", methodObject),
		new Among("cht\u011Bje", 18, 8, "", methodObject),
		new Among("cht\u011Bjme", 18, 8, "", methodObject),
		new Among("cht\u011Bjte", 18, 8, "", methodObject),
		new Among("cht\u011Bj\u00ED", 18, 8, "", methodObject),
		new Among("cht\u011Bj\u00EDc", 22, 8, "", methodObject),
		new Among("cht\u011Bj\u00EDce", 23, 8, "", methodObject),
		new Among("cht\u011Bl", 17, 8, "", methodObject),
		new Among("cht\u011Bn", 17, 8, "", methodObject),
		new Among("jda", -1, 3, "", methodObject),
		new Among("jde", -1, 3, "", methodObject),
		new Among("jdeme", 28, 3, "", methodObject),
		new Among("jdete", 28, 3, "", methodObject),
		new Among("jde\u0161", 28, 3, "", methodObject),
		new Among("jdi", -1, 3, "", methodObject),
		new Among("jdou", -1, 3, "", methodObject),
		new Among("jdouc", 33, 3, "", methodObject),
		new Among("jdouce", 34, 3, "", methodObject),
		new Among("jdu", -1, 3, "", methodObject),
		new Among("jd\u011Bme", -1, 3, "", methodObject),
		new Among("jd\u011Bte", -1, 3, "", methodObject),
		new Among("je", -1, 1, "", methodObject),
		new Among("jeda", 39, 4, "", methodObject),
		new Among("jeden", 39, 4, "", methodObject),
		new Among("jedl", 39, 4, "", methodObject),
		new Among("jedouc", 39, 4, "", methodObject),
		new Among("jedouce", 43, 4, "", methodObject),
		new Among("jed\u00ED", 39, 4, "", methodObject),
		new Among("jez", 39, 4, "", methodObject),
		new Among("jezme", 46, 4, "", methodObject),
		new Among("jezte", 46, 4, "", methodObject),
		new Among("jsa", -1, 1, "", methodObject),
		new Among("jsem", -1, 1, "", methodObject),
		new Among("jsi", -1, 1, "", methodObject),
		new Among("jsme", -1, 1, "", methodObject),
		new Among("jsou", -1, 1, "", methodObject),
		new Among("jsouc", 53, 1, "", methodObject),
		new Among("jsouce", 54, 1, "", methodObject),
		new Among("jste", -1, 1, "", methodObject),
		new Among("j\u00ED", -1, 4, "", methodObject),
		new Among("j\u00EDm", 57, 4, "", methodObject),
		new Among("j\u00EDme", 58, 4, "", methodObject),
		new Among("j\u00EDte", 57, 4, "", methodObject),
		new Among("j\u00ED\u0161", 57, 4, "", methodObject),
		new Among("maje", -1, 2, "", methodObject),
		new Among("maj\u00ED", -1, 2, "", methodObject),
		new Among("maj\u00EDc", 63, 2, "", methodObject),
		new Among("maj\u00EDce", 64, 2, "", methodObject),
		new Among("m\u00E1", -1, 2, "", methodObject),
		new Among("m\u00E1m", 66, 2, "", methodObject),
		new Among("m\u00E1me", 67, 2, "", methodObject),
		new Among("m\u00E1te", 66, 2, "", methodObject),
		new Among("m\u00E1\u0161", 66, 2, "", methodObject),
		new Among("m\u011Bj", -1, 2, "", methodObject),
		new Among("m\u011Bjme", 71, 2, "", methodObject),
		new Among("m\u011Bjte", 71, 2, "", methodObject),
		new Among("m\u011Bl", -1, 2, "", methodObject),
		new Among("poj\u010F", -1, 3, "", methodObject),
		new Among("poj\u010Fte", 75, 3, "", methodObject),
		new Among("p\u016Fjde", -1, 3, "", methodObject),
		new Among("p\u016Fjdeme", 77, 3, "", methodObject),
		new Among("p\u016Fjdete", 77, 3, "", methodObject),
		new Among("p\u016Fjde\u0161", 77, 3, "", methodObject),
		new Among("p\u016Fjdou", -1, 3, "", methodObject),
		new Among("p\u016Fjdu", -1, 3, "", methodObject),
		new Among("sn\u00ED", -1, 5, "", methodObject),
		new Among("sn\u00EDm", 83, 5, "", methodObject),
		new Among("sn\u00EDme", 84, 5, "", methodObject),
		new Among("sn\u00EDte", 83, 5, "", methodObject),
		new Among("sn\u00ED\u0161", 83, 5, "", methodObject),
		new Among("sn\u011Bden", -1, 5, "", methodObject),
		new Among("sn\u011Bdl", -1, 5, "", methodObject),
		new Among("sn\u011Bd\u00ED", -1, 5, "", methodObject),
		new Among("sn\u011Bz", -1, 5, "", methodObject),
		new Among("sn\u011Bzme", 91, 5, "", methodObject),
		new Among("sn\u011Bzte", 91, 5, "", methodObject),
		new Among("vida", -1, 6, "", methodObject),
		new Among("vidouc", -1, 6, "", methodObject),
		new Among("vidouce", 95, 6, "", methodObject),
		new Among("vid\u00ED", -1, 6, "", methodObject),
		new Among("vid\u00EDm", 97, 6, "", methodObject),
		new Among("vid\u00EDme", 98, 6, "", methodObject),
		new Among("vid\u00EDte", 97, 6, "", methodObject),
		new Among("vid\u00ED\u0161", 97, 6, "", methodObject),
		new Among("vid\u011Bl", -1, 6, "", methodObject),
		new Among("vid\u011Bn", -1, 6, "", methodObject),
		new Among("viz", -1, 6, "", methodObject),
		new Among("vizme", 104, 6, "", methodObject),
		new Among("vizte", 104, 6, "", methodObject),
		new Among("v\u00ED", -1, 7, "", methodObject),
		new Among("v\u00EDm", 107, 7, "", methodObject),
		new Among("v\u00EDme", 108, 7, "", methodObject),
		new Among("v\u00EDte", 107, 7, "", methodObject),
		new Among("v\u00ED\u0161", 107, 7, "", methodObject),
		new Among("v\u011Bda", -1, 7, "", methodObject),
		new Among("v\u011Bdouc", -1, 7, "", methodObject),
		new Among("v\u011Bdouce", 113, 7, "", methodObject),
		new Among("v\u011Bd\u00ED", -1, 7, "", methodObject),
		new Among("v\u011Bd\u011Bl", -1, 7, "", methodObject),
		new Among("v\u011Bd\u011Bn", -1, 7, "", methodObject),
		new Among("v\u011Bz", -1, 7, "", methodObject),
		new Among("v\u011Bzme", 118, 7, "", methodObject),
		new Among("v\u011Bzte", 118, 7, "", methodObject),
		new Among("\u0161el", -1, 3, "", methodObject),
		new Among("\u0161la", -1, 3, "", methodObject),
		new Among("\u0161li", -1, 3, "", methodObject),
		new Among("\u0161lo", -1, 3, "", methodObject)
	};
	private final static Among a_2[] = {
		new Among("ba", -1, 3, "", methodObject),
		new Among("oba", 0, 3, "", methodObject),
		new Among("tba", 0, 3, "", methodObject),
		new Among("itba", 2, 1, "", methodObject),
		new Among("nda", -1, 3, "", methodObject),
		new Among("ucha", -1, 3, "", methodObject),
		new Among("ka", -1, 3, "", methodObject),
		new Among("ika", 6, 1, "", methodObject),
		new Among("nka", 6, 3, "", methodObject),
		new Among("enka", 8, 3, "", methodObject),
		new Among("inka", 8, 1, "", methodObject),
		new Among("\u011Bnka", 8, 3, "", methodObject),
		new Among("tka", 6, 3, "", methodObject),
		new Among("vka", 6, 3, "", methodObject),
		new Among("t\u00E9ka", 6, 3, "", methodObject),
		new Among("\u010Dka", 6, 3, "", methodObject),
		new Among("e\u010Dka", 15, 3, "", methodObject),
		new Among("\u00ED\u010Dka", 15, 3, "", methodObject),
		new Among("u\u0161ka", 6, 3, "", methodObject),
		new Among("ala", -1, 3, "", methodObject),
		new Among("\u00E1la", -1, 3, "", methodObject),
		new Among("na", -1, 3, "", methodObject),
		new Among("ina", 21, 1, "", methodObject),
		new Among("tina", 22, 3, "", methodObject),
		new Among("\u0161tina", 23, 3, "", methodObject),
		new Among("ovina", 22, 3, "", methodObject),
		new Among("telna", 21, 3, "", methodObject),
		new Among("\u00E1rna", 21, 3, "", methodObject),
		new Among("\u00EDrna", 21, 3, "", methodObject),
		new Among("ovna", 21, 3, "", methodObject),
		new Among("izna", 21, 1, "", methodObject),
		new Among("ajzna", 21, 3, "", methodObject),
		new Among("ura", -1, 3, "", methodObject),
		new Among("tura", 32, 3, "", methodObject),
		new Among("ita", -1, 1, "", methodObject),
		new Among("ota", -1, 3, "", methodObject),
		new Among("ista", -1, 1, "", methodObject),
		new Among("tva", -1, 3, "", methodObject),
		new Among("ec", -1, 3, "", methodObject),
		new Among("inec", 38, 1, "", methodObject),
		new Among("obinec", 39, 3, "", methodObject),
		new Among("tec", 38, 3, "", methodObject),
		new Among("ovec", 38, 3, "", methodObject),
		new Among("\u0159ad", -1, 3, "", methodObject),
		new Among("vod", -1, 3, "", methodObject),
		new Among("ce", -1, 3, "", methodObject),
		new Among("ace", 45, 3, "", methodObject),
		new Among("ice", 45, 1, "", methodObject),
		new Among("nice", 47, 3, "", methodObject),
		new Among("enice", 48, 3, "", methodObject),
		new Among("nce", 45, 3, "", methodObject),
		new Among("ance", 50, 3, "", methodObject),
		new Among("ence", 50, 3, "", methodObject),
		new Among("ie", -1, 1, "", methodObject),
		new Among("erie", 53, 3, "", methodObject),
		new Among("ule", -1, 3, "", methodObject),
		new Among("se", -1, 3, "", methodObject),
		new Among("xe", -1, 3, "", methodObject),
		new Among("ze", -1, 3, "", methodObject),
		new Among("\u010De", -1, 3, "", methodObject),
		new Among("graf", -1, 3, "", methodObject),
		new Among("ing", -1, 1, "", methodObject),
		new Among("log", -1, 3, "", methodObject),
		new Among("och", -1, 3, "", methodObject),
		new Among("ek", -1, 3, "", methodObject),
		new Among("\u00E1nek", 64, 3, "", methodObject),
		new Among("\u00EDnek", 64, 3, "", methodObject),
		new Among("\u00E1sek", 64, 3, "", methodObject),
		new Among("e\u010Dek", 64, 3, "", methodObject),
		new Among("\u00E1\u010Dek", 64, 3, "", methodObject),
		new Among("\u00ED\u010Dek", 64, 3, "", methodObject),
		new Among("ou\u0161ek", 64, 3, "", methodObject),
		new Among("ik", -1, 1, "", methodObject),
		new Among("ink", -1, 1, "", methodObject),
		new Among("unk", -1, 3, "", methodObject),
		new Among("\u00E1k", -1, 3, "", methodObject),
		new Among("\u00EDk", -1, 3, "", methodObject),
		new Among("n\u00EDk", 76, 2, "", methodObject),
		new Among("ovn\u00EDk", 77, 3, "", methodObject),
		new Among("u\u0148k", -1, 3, "", methodObject),
		new Among("tel", -1, 3, "", methodObject),
		new Among("ovatel", 80, 3, "", methodObject),
		new Among("itel", 80, 1, "", methodObject),
		new Among("\u00E1l", -1, 3, "", methodObject),
		new Among("nom", -1, 3, "", methodObject),
		new Among("ium", -1, 1, "", methodObject),
		new Among("ikum", -1, 1, "", methodObject),
		new Among("ivum", -1, 1, "", methodObject),
		new Among("an", -1, 3, "", methodObject),
		new Among("\u010Dan", 88, 3, "", methodObject),
		new Among("oun", -1, 3, "", methodObject),
		new Among("loun", 90, 3, "", methodObject),
		new Among("\u00E1n", -1, 3, "", methodObject),
		new Among("i\u00E1n", 92, 1, "", methodObject),
		new Among("\u00EDn", -1, 3, "", methodObject),
		new Among("ko", -1, 3, "", methodObject),
		new Among("isko", 95, 1, "", methodObject),
		new Among("ovisko", 96, 3, "", methodObject),
		new Among("tko", 95, 3, "", methodObject),
		new Among("\u00E1tko", 98, 3, "", methodObject),
		new Among("e\u010Dko", 95, 3, "", methodObject),
		new Among("\u00E9\u010Dko", 95, 3, "", methodObject),
		new Among("\u00ED\u010Dko", 95, 3, "", methodObject),
		new Among("lo", -1, 3, "", methodObject),
		new Among("dlo", 103, 3, "", methodObject),
		new Among("no", -1, 3, "", methodObject),
		new Among("\u010Dno", 105, 3, "", methodObject),
		new Among("ivo", -1, 1, "", methodObject),
		new Among("tvo", -1, 3, "", methodObject),
		new Among("stvo", 108, 3, "", methodObject),
		new Among("ovstvo", 109, 3, "", methodObject),
		new Among("er", -1, 3, "", methodObject),
		new Among("or", -1, 3, "", methodObject),
		new Among("tor", 112, 3, "", methodObject),
		new Among("\u00E1tor", 113, 3, "", methodObject),
		new Among("our", -1, 3, "", methodObject),
		new Among("\u00E9r", -1, 3, "", methodObject),
		new Among("i\u00E9r", 116, 1, "", methodObject),
		new Among("at\u00E9r", 116, 3, "", methodObject),
		new Among("m\u011Br", -1, 3, "", methodObject),
		new Among("as", -1, 3, "", methodObject),
		new Among("ismus", -1, 1, "", methodObject),
		new Among("met", -1, 3, "", methodObject),
		new Among("ant", -1, 3, "", methodObject),
		new Among("ent", -1, 3, "", methodObject),
		new Among("ment", 124, 3, "", methodObject),
		new Among("ot", -1, 3, "", methodObject),
		new Among("est", -1, 3, "", methodObject),
		new Among("ost", -1, 3, "", methodObject),
		new Among("nost", 128, 3, "", methodObject),
		new Among("out", -1, 3, "", methodObject),
		new Among("\u00E1t", -1, 3, "", methodObject),
		new Among("ov", -1, 3, "", methodObject),
		new Among("iny", -1, 1, "", methodObject),
		new Among("n\u00E1", -1, 3, "", methodObject),
		new Among("ov\u00E1", -1, 3, "", methodObject),
		new Among("n\u00E9", -1, 3, "", methodObject),
		new Among("ovn\u00E9", 136, 3, "", methodObject),
		new Among("\u0159ad\u00ED", -1, 3, "", methodObject),
		new Among("n\u00ED", -1, 3, "", methodObject),
		new Among("an\u00ED", 139, 3, "", methodObject),
		new Among("en\u00ED", 139, 3, "", methodObject),
		new Among("\u00E1n\u00ED", 139, 3, "", methodObject),
		new Among("\u011Bn\u00ED", 139, 3, "", methodObject),
		new Among("t\u00ED", -1, 3, "", methodObject),
		new Among("et\u00ED", 144, 3, "", methodObject),
		new Among("\u011Bt\u00ED", 144, 3, "", methodObject),
		new Among("ov\u00ED", -1, 3, "", methodObject),
		new Among("slov\u00ED", 147, 3, "", methodObject),
		new Among("ctv\u00ED", -1, 3, "", methodObject),
		new Among("stv\u00ED", -1, 3, "", methodObject),
		new Among("\u010D\u00ED", -1, 3, "", methodObject),
		new Among("\u00E1\u010D", -1, 3, "", methodObject),
		new Among("yn\u011B", -1, 3, "", methodObject),
		new Among("kyn\u011B", 153, 3, "", methodObject),
		new Among("i\u0161t\u011B", -1, 1, "", methodObject),
		new Among("ovi\u0161t\u011B", 155, 3, "", methodObject),
		new Among("o\u0148", -1, 3, "", methodObject),
		new Among("a\u0159", -1, 3, "", methodObject),
		new Among("to\u0159", -1, 3, "", methodObject),
		new Among("\u00E1\u0159", -1, 3, "", methodObject),
		new Among("k\u00E1\u0159", 160, 3, "", methodObject),
		new Among("ion\u00E1\u0159", 160, 1, "", methodObject),
		new Among("\u00E9\u0159", -1, 3, "", methodObject),
		new Among("n\u00E9\u0159", 163, 3, "", methodObject),
		new Among("\u00ED\u0159", -1, 3, "", methodObject),
		new Among("\u00FD\u0159", -1, 3, "", methodObject),
		new Among("ou\u0161", -1, 3, "", methodObject),
		new Among("\u00FD\u0161", -1, 3, "", methodObject),
		new Among("\u00E1\u017E", -1, 3, "", methodObject)
	};
	private final static Among a_3[] = {
		new Among("a", -1, 17, "", methodObject),
		new Among("ba", 0, 17, "", methodObject),
		new Among("ga", 0, 11, "", methodObject),
		new Among("ka", 0, 17, "", methodObject),
		new Among("la", 0, 3, "", methodObject),
		new Among("na", 0, 17, "", methodObject),
		new Among("ra", 0, 17, "", methodObject),
		new Among("ata", 0, 17, "", methodObject),
		new Among("va", 0, 17, "", methodObject),
		new Among("eb", -1, 1, "", methodObject),
		new Among("ec", -1, 17, "", methodObject),
		new Among("e", -1, 17, "", methodObject),
		new Among("ce", 11, 17, "", methodObject),
		new Among("le", 11, 3, "", methodObject),
		new Among("ete", 11, 6, "", methodObject),
		new Among("\u011Bte", 11, 15, "", methodObject),
		new Among("\u010De", 11, 2, "", methodObject),
		new Among("g", -1, 17, "", methodObject),
		new Among("ech", -1, 17, "", methodObject),
		new Among("lech", 18, 3, "", methodObject),
		new Among("nech", 18, 7, "", methodObject),
		new Among("atech", 18, 17, "", methodObject),
		new Among("vech", 18, 12, "", methodObject),
		new Among("\u00E1ch", -1, 13, "", methodObject),
		new Among("b\u00E1ch", 23, 1, "", methodObject),
		new Among("k\u00E1ch", 23, 17, "", methodObject),
		new Among("n\u00E1ch", 23, 5, "", methodObject),
		new Among("r\u00E1ch", 23, 4, "", methodObject),
		new Among("v\u00E1ch", 23, 8, "", methodObject),
		new Among("\u00EDch", -1, 17, "", methodObject),
		new Among("c\u00EDch", 29, 17, "", methodObject),
		new Among("n\u00EDch", 29, 17, "", methodObject),
		new Among("t\u00EDch", 29, 10, "", methodObject),
		new Among("z\u00EDch", 29, 17, "", methodObject),
		new Among("i", -1, 17, "", methodObject),
		new Among("ci", 34, 17, "", methodObject),
		new Among("ami", 34, 13, "", methodObject),
		new Among("bami", 36, 1, "", methodObject),
		new Among("kami", 36, 16, "", methodObject),
		new Among("nami", 36, 5, "", methodObject),
		new Among("rami", 36, 4, "", methodObject),
		new Among("vami", 36, 8, "", methodObject),
		new Among("emi", 34, 17, "", methodObject),
		new Among("\u011Bmi", 34, 15, "", methodObject),
		new Among("n\u011Bmi", 43, 14, "", methodObject),
		new Among("ni", 34, 17, "", methodObject),
		new Among("ti", 34, 10, "", methodObject),
		new Among("eti", 46, 6, "", methodObject),
		new Among("\u011Bti", 46, 15, "", methodObject),
		new Among("ovi", 34, 17, "", methodObject),
		new Among("govi", 49, 11, "", methodObject),
		new Among("kovi", 49, 9, "", methodObject),
		new Among("zi", 34, 17, "", methodObject),
		new Among("k", -1, 17, "", methodObject),
		new Among("ek", 53, 17, "", methodObject),
		new Among("el", -1, 3, "", methodObject),
		new Among("em", -1, 17, "", methodObject),
		new Among("cem", 56, 2, "", methodObject),
		new Among("gem", 56, 11, "", methodObject),
		new Among("kem", 56, 17, "", methodObject),
		new Among("lem", 56, 3, "", methodObject),
		new Among("nem", 56, 7, "", methodObject),
		new Among("etem", 56, 6, "", methodObject),
		new Among("\u011Btem", 56, 15, "", methodObject),
		new Among("vem", 56, 12, "", methodObject),
		new Among("um", -1, 17, "", methodObject),
		new Among("kum", 65, 17, "", methodObject),
		new Among("\u00E1m", -1, 13, "", methodObject),
		new Among("b\u00E1m", 67, 1, "", methodObject),
		new Among("k\u00E1m", 67, 16, "", methodObject),
		new Among("n\u00E1m", 67, 5, "", methodObject),
		new Among("r\u00E1m", 67, 4, "", methodObject),
		new Among("v\u00E1m", 67, 8, "", methodObject),
		new Among("\u00EDm", -1, 17, "", methodObject),
		new Among("n\u00EDm", 73, 17, "", methodObject),
		new Among("t\u00EDm", 73, 10, "", methodObject),
		new Among("t\u011Bm", -1, 10, "", methodObject),
		new Among("\u016Fm", -1, 17, "", methodObject),
		new Among("c\u016Fm", 77, 2, "", methodObject),
		new Among("g\u016Fm", 77, 11, "", methodObject),
		new Among("k\u016Fm", 77, 17, "", methodObject),
		new Among("l\u016Fm", 77, 3, "", methodObject),
		new Among("n\u016Fm", 77, 7, "", methodObject),
		new Among("at\u016Fm", 77, 17, "", methodObject),
		new Among("v\u016Fm", 77, 12, "", methodObject),
		new Among("en", -1, 17, "", methodObject),
		new Among("o", -1, 17, "", methodObject),
		new Among("bo", 86, 1, "", methodObject),
		new Among("ko", 86, 17, "", methodObject),
		new Among("lo", 86, 17, "", methodObject),
		new Among("no", 86, 17, "", methodObject),
		new Among("ro", 86, 4, "", methodObject),
		new Among("vo", 86, 17, "", methodObject),
		new Among("r", -1, 4, "", methodObject),
		new Among("at", -1, 17, "", methodObject),
		new Among("u", -1, 17, "", methodObject),
		new Among("bu", 95, 1, "", methodObject),
		new Among("gu", 95, 11, "", methodObject),
		new Among("ku", 95, 17, "", methodObject),
		new Among("lu", 95, 3, "", methodObject),
		new Among("nu", 95, 17, "", methodObject),
		new Among("ou", 95, 13, "", methodObject),
		new Among("bou", 101, 1, "", methodObject),
		new Among("kou", 101, 16, "", methodObject),
		new Among("nou", 101, 5, "", methodObject),
		new Among("rou", 101, 4, "", methodObject),
		new Among("vou", 101, 8, "", methodObject),
		new Among("ru", 95, 4, "", methodObject),
		new Among("vu", 95, 17, "", methodObject),
		new Among("ev", -1, 17, "", methodObject),
		new Among("y", -1, 17, "", methodObject),
		new Among("by", 110, 1, "", methodObject),
		new Among("gy", 110, 11, "", methodObject),
		new Among("ky", 110, 17, "", methodObject),
		new Among("ly", 110, 3, "", methodObject),
		new Among("ny", 110, 17, "", methodObject),
		new Among("ry", 110, 4, "", methodObject),
		new Among("aty", 110, 17, "", methodObject),
		new Among("vy", 110, 17, "", methodObject),
		new Among("\u00E9", -1, 17, "", methodObject),
		new Among("ov\u00E9", 119, 17, "", methodObject),
		new Among("gov\u00E9", 120, 11, "", methodObject),
		new Among("\u00ED", -1, 17, "", methodObject),
		new Among("n\u00ED", 122, 17, "", methodObject),
		new Among("\u011B", -1, 17, "", methodObject),
		new Among("b\u011B", 124, 1, "", methodObject),
		new Among("n\u011B", 124, 17, "", methodObject),
		new Among("t\u011B", 124, 17, "", methodObject),
		new Among("v\u011B", 124, 8, "", methodObject),
		new Among("\u0148", -1, 17, "", methodObject),
		new Among("e\u0148", 129, 17, "", methodObject),
		new Among("\u0165", -1, 10, "", methodObject),
		new Among("\u016F", -1, 17, "", methodObject),
		new Among("c\u016F", 132, 2, "", methodObject),
		new Among("g\u016F", 132, 11, "", methodObject),
		new Among("k\u016F", 132, 17, "", methodObject)
	};
	private final static Among a_4[] = {
		new Among("ina", -1, 2, "", methodObject),
		new Among("ova", -1, 1, "", methodObject),
		new Among("ovic", -1, 1, "", methodObject),
		new Among("in", -1, 2, "", methodObject),
		new Among("ino", -1, 2, "", methodObject),
		new Among("ovo", -1, 1, "", methodObject),
		new Among("\u016Fv", -1, 1, "", methodObject),
		new Among("c\u00ED", -1, 1, "", methodObject),
		new Among("ac\u00ED", 7, 1, "", methodObject),
		new Among("ic\u00ED", 7, 1, "", methodObject),
		new Among("n\u00ED", -1, 4, "", methodObject),
		new Among("biln\u00ED", 10, 1, "", methodObject),
		new Among("\u00E1ln\u00ED", 10, 1, "", methodObject),
		new Among("\u00E1rn\u00ED", 10, 1, "", methodObject),
		new Among("tn\u00ED", 10, 1, "", methodObject),
		new Among("ntn\u00ED", 14, 1, "", methodObject),
		new Among("ivn\u00ED", 10, 1, "", methodObject),
		new Among("ovn\u00ED", 10, 1, "", methodObject),
		new Among("a\u010Dn\u00ED", 10, 1, "", methodObject),
		new Among("e\u010Dn\u00ED", 10, 1, "", methodObject),
		new Among("i\u010Dn\u00ED", 10, 1, "", methodObject),
		new Among("ov\u00ED", -1, 1, "", methodObject),
		new Among("\u010D\u00ED", -1, 1, "", methodObject),
		new Among("\u0161\u00ED", -1, 1, "", methodObject),
		new Among("ej\u0161\u00ED", 23, 6, "", methodObject),
		new Among("\u011Bj\u0161\u00ED", 23, 6, "", methodObject),
		new Among("n\u011Bj\u0161\u00ED", 25, 1, "", methodObject),
		new Among("ovn\u011Bj\u0161\u00ED", 26, 1, "", methodObject),
		new Among("t\u011Bj\u0161\u00ED", 25, 1, "", methodObject),
		new Among("\u0161t\u011Bj\u0161\u00ED", 28, 3, "", methodObject),
		new Among("ij\u0161t\u011Bj\u0161\u00ED", 29, 3, "", methodObject),
		new Among("ov\u0161t\u011Bj\u0161\u00ED", 29, 1, "", methodObject),
		new Among("ov\u011Bj\u0161\u00ED", 25, 1, "", methodObject),
		new Among("k\u00FD", -1, 3, "", methodObject),
		new Among("ck\u00FD", 33, 1, "", methodObject),
		new Among("ick\u00FD", 34, 1, "", methodObject),
		new Among("ink\u00FD", 33, 2, "", methodObject),
		new Among("ilink\u00FD", 36, 1, "", methodObject),
		new Among("oulink\u00FD", 36, 1, "", methodObject),
		new Among("ounink\u00FD", 36, 1, "", methodObject),
		new Among("ounk\u00FD", 33, 1, "", methodObject),
		new Among("sk\u00FD", 33, 3, "", methodObject),
		new Among("ijsk\u00FD", 41, 1, "", methodObject),
		new Among("\u00E1nsk\u00FD", 41, 1, "", methodObject),
		new Among("ovsk\u00FD", 41, 3, "", methodObject),
		new Among("i\u010Dk\u00FD", 33, 2, "", methodObject),
		new Among("i\u010Di\u010Dk\u00FD", 45, 1, "", methodObject),
		new Among("ou\u010Dk\u00FD", 33, 1, "", methodObject),
		new Among("l\u00FD", -1, 1, "", methodObject),
		new Among("i\u010Del\u00FD", 48, 1, "", methodObject),
		new Among("il\u00FD", 48, 1, "", methodObject),
		new Among("n\u00FD", -1, 4, "", methodObject),
		new Among("ovan\u00FD", 51, 1, "", methodObject),
		new Among("cn\u00FD", 51, 1, "", methodObject),
		new Among("en\u00FD", 51, 1, "", methodObject),
		new Among("teln\u00FD", 51, 1, "", methodObject),
		new Among("iteln\u00FD", 55, 4, "", methodObject),
		new Among("tn\u00FD", 51, 1, "", methodObject),
		new Among("utn\u00FD", 57, 1, "", methodObject),
		new Among("e\u010Dn\u00FD", 51, 1, "", methodObject),
		new Among("i\u010Dn\u00FD", 51, 1, "", methodObject),
		new Among("\u011Bn\u00FD", 51, 1, "", methodObject),
		new Among("at\u00FD", -1, 1, "", methodObject),
		new Among("inkat\u00FD", 62, 1, "", methodObject),
		new Among("nat\u00FD", 62, 5, "", methodObject),
		new Among("it\u00FD", -1, 2, "", methodObject),
		new Among("ovit\u00FD", 65, 1, "", methodObject),
		new Among("i\u010Dit\u00FD", 65, 1, "", methodObject),
		new Among("ist\u00FD", -1, 1, "", methodObject),
		new Among("ut\u00FD", -1, 1, "", methodObject),
		new Among("v\u00FD", -1, 1, "", methodObject),
		new Among("av\u00FD", 70, 1, "", methodObject),
		new Among("kav\u00FD", 71, 1, "", methodObject),
		new Among("lav\u00FD", 71, 1, "", methodObject),
		new Among("iv\u00FD", 70, 2, "", methodObject),
		new Among("liv\u00FD", 74, 1, "", methodObject),
		new Among("ov\u00FD", 70, 1, "", methodObject)
	};
	private final static Among a_5[] = {
		new Among("ina", -1, 11, "", methodObject),
		new Among("ova", -1, 9, "", methodObject),
		new Among("\u00EDch", -1, 8, "", methodObject),
		new Among("\u00FDch", -1, 10, "", methodObject),
		new Among("h\u00FDch", 3, 5, "", methodObject),
		new Among("ch\u00FDch", 4, 4, "", methodObject),
		new Among("k\u00FDch", 3, 3, "", methodObject),
		new Among("ck\u00FDch", 6, 2, "", methodObject),
		new Among("sk\u00FDch", 6, 1, "", methodObject),
		new Among("in\u00FDch", 3, 11, "", methodObject),
		new Among("r\u00FDch", 3, 6, "", methodObject),
		new Among("ov\u00FDch", 3, 9, "", methodObject),
		new Among("\u00EDmi", -1, 8, "", methodObject),
		new Among("\u00FDmi", -1, 10, "", methodObject),
		new Among("h\u00FDmi", 13, 5, "", methodObject),
		new Among("ch\u00FDmi", 14, 4, "", methodObject),
		new Among("k\u00FDmi", 13, 3, "", methodObject),
		new Among("ck\u00FDmi", 16, 2, "", methodObject),
		new Among("sk\u00FDmi", 16, 1, "", methodObject),
		new Among("in\u00FDmi", 13, 11, "", methodObject),
		new Among("r\u00FDmi", 13, 6, "", methodObject),
		new Among("ov\u00FDmi", 13, 9, "", methodObject),
		new Among("ini", -1, 11, "", methodObject),
		new Among("ovi", -1, 9, "", methodObject),
		new Among("\u00E9m", -1, 10, "", methodObject),
		new Among("h\u00E9m", 24, 5, "", methodObject),
		new Among("ch\u00E9m", 25, 4, "", methodObject),
		new Among("k\u00E9m", 24, 3, "", methodObject),
		new Among("ck\u00E9m", 27, 2, "", methodObject),
		new Among("sk\u00E9m", 27, 1, "", methodObject),
		new Among("r\u00E9m", 24, 6, "", methodObject),
		new Among("\u00EDm", -1, 8, "", methodObject),
		new Among("\u00FDm", -1, 10, "", methodObject),
		new Among("h\u00FDm", 32, 5, "", methodObject),
		new Among("ch\u00FDm", 33, 4, "", methodObject),
		new Among("k\u00FDm", 32, 3, "", methodObject),
		new Among("ck\u00FDm", 35, 2, "", methodObject),
		new Among("sk\u00FDm", 35, 1, "", methodObject),
		new Among("in\u00FDm", 32, 11, "", methodObject),
		new Among("r\u00FDm", 32, 6, "", methodObject),
		new Among("ov\u00FDm", 32, 9, "", methodObject),
		new Among("in", -1, 11, "", methodObject),
		new Among("\u00E9ho", -1, 10, "", methodObject),
		new Among("h\u00E9ho", 42, 5, "", methodObject),
		new Among("ch\u00E9ho", 43, 4, "", methodObject),
		new Among("k\u00E9ho", 42, 3, "", methodObject),
		new Among("ck\u00E9ho", 45, 2, "", methodObject),
		new Among("sk\u00E9ho", 45, 1, "", methodObject),
		new Among("r\u00E9ho", 42, 6, "", methodObject),
		new Among("\u00EDho", -1, 8, "", methodObject),
		new Among("ino", -1, 11, "", methodObject),
		new Among("ovo", -1, 9, "", methodObject),
		new Among("\u00E9mu", -1, 10, "", methodObject),
		new Among("h\u00E9mu", 52, 5, "", methodObject),
		new Among("ch\u00E9mu", 53, 4, "", methodObject),
		new Among("k\u00E9mu", 52, 3, "", methodObject),
		new Among("ck\u00E9mu", 55, 2, "", methodObject),
		new Among("sk\u00E9mu", 55, 1, "", methodObject),
		new Among("r\u00E9mu", 52, 6, "", methodObject),
		new Among("\u00EDmu", -1, 8, "", methodObject),
		new Among("inu", -1, 11, "", methodObject),
		new Among("ou", -1, 10, "", methodObject),
		new Among("hou", 61, 5, "", methodObject),
		new Among("chou", 62, 4, "", methodObject),
		new Among("kou", 61, 3, "", methodObject),
		new Among("ckou", 64, 2, "", methodObject),
		new Among("skou", 64, 1, "", methodObject),
		new Among("inou", 61, 11, "", methodObject),
		new Among("rou", 61, 6, "", methodObject),
		new Among("ovou", 61, 9, "", methodObject),
		new Among("ovu", -1, 9, "", methodObject),
		new Among("\u016Fv", -1, 9, "", methodObject),
		new Among("iny", -1, 11, "", methodObject),
		new Among("ovy", -1, 9, "", methodObject),
		new Among("\u00E1", -1, 10, "", methodObject),
		new Among("h\u00E1", 74, 5, "", methodObject),
		new Among("ch\u00E1", 75, 4, "", methodObject),
		new Among("k\u00E1", 74, 3, "", methodObject),
		new Among("ck\u00E1", 77, 2, "", methodObject),
		new Among("sk\u00E1", 77, 1, "", methodObject),
		new Among("r\u00E1", 74, 6, "", methodObject),
		new Among("\u00E9", -1, 10, "", methodObject),
		new Among("h\u00E9", 81, 5, "", methodObject),
		new Among("ch\u00E9", 82, 4, "", methodObject),
		new Among("k\u00E9", 81, 3, "", methodObject),
		new Among("ck\u00E9", 84, 2, "", methodObject),
		new Among("sk\u00E9", 84, 1, "", methodObject),
		new Among("r\u00E9", 81, 6, "", methodObject),
		new Among("\u00ED", -1, 12, "", methodObject),
		new Among("c\u00ED", 88, 3, "", methodObject),
		new Among("\u010Dt\u00ED", 88, 2, "", methodObject),
		new Among("\u0161t\u00ED", 88, 1, "", methodObject),
		new Among("av\u00ED", 88, 7, "", methodObject),
		new Among("\u0159\u00ED", 88, 6, "", methodObject),
		new Among("ej\u0161\u00ED", 88, 10, "", methodObject),
		new Among("\u0159ej\u0161\u00ED", 94, 6, "", methodObject),
		new Among("\u011Bj\u0161\u00ED", 88, 10, "", methodObject),
		new Among("\u010Dt\u011Bj\u0161\u00ED", 96, 2, "", methodObject),
		new Among("\u0161t\u011Bj\u0161\u00ED", 96, 1, "", methodObject),
		new Among("r\u0161\u00ED", 88, 6, "", methodObject),
		new Among("\u0161\u0161\u00ED", 88, 4, "", methodObject),
		new Among("\u017E\u0161\u00ED", 88, 5, "", methodObject),
		new Among("\u00FD", -1, 10, "", methodObject),
		new Among("h\u00FD", 102, 5, "", methodObject),
		new Among("ch\u00FD", 103, 4, "", methodObject),
		new Among("k\u00FD", 102, 3, "", methodObject),
		new Among("ck\u00FD", 105, 2, "", methodObject),
		new Among("sk\u00FD", 105, 1, "", methodObject),
		new Among("r\u00FD", 102, 6, "", methodObject),
		new Among("in\u011B", -1, 11, "", methodObject),
		new Among("ov\u011B", -1, 9, "", methodObject)
	};
	private final static Among a_6[] = {
		new Among("t", -1, 1, "", methodObject),
		new Among("at", 0, 1, "", methodObject),
		new Among("ovat", 1, 1, "", methodObject),
		new Among("zat", 1, 1, "", methodObject),
		new Among("ct", 0, 1, "", methodObject),
		new Among("et", 0, 1, "", methodObject),
		new Among("it", 0, 1, "", methodObject),
		new Among("dit", 6, 1, "", methodObject),
		new Among("sit", 6, 1, "", methodObject),
		new Among("stit", 6, 1, "", methodObject),
		new Among("nout", 0, 1, "", methodObject),
		new Among("sknout", 10, 1, "", methodObject),
		new Among("r\u00E1t", 0, 1, "", methodObject),
		new Among("\u0159\u00EDt", 0, 1, "", methodObject),
		new Among("\u011Bt", 0, 1, "", methodObject)
	};
	private final static Among a_7[] = {
		new Among("a", -1, 3, "", methodObject),
		new Among("ka", 0, 6, "", methodObject),
		new Among("la", 0, 3, "", methodObject),
		new Among("ala", 2, 16, "", methodObject),
		new Among("rala", 3, 2, "", methodObject),
		new Among("ovala", 3, 1, "", methodObject),
		new Among("zala", 3, 4, "", methodObject),
		new Among("ela", 2, 8, "", methodObject),
		new Among("\u0159ela", 7, 11, "", methodObject),
		new Among("ila", 2, 13, "", methodObject),
		new Among("dila", 9, 15, "", methodObject),
		new Among("sila", 9, 7, "", methodObject),
		new Among("stila", 9, 14, "", methodObject),
		new Among("zila", 9, 13, "", methodObject),
		new Among("kla", 2, 6, "", methodObject),
		new Among("skla", 14, 9, "", methodObject),
		new Among("nula", 2, 5, "", methodObject),
		new Among("\u011Bla", 2, 10, "", methodObject),
		new Among("na", 0, 5, "", methodObject),
		new Among("ena", 18, 16, "", methodObject),
		new Among("zena", 19, 15, "", methodObject),
		new Among("\u010Dena", 19, 6, "", methodObject),
		new Among("\u0159ena", 19, 11, "", methodObject),
		new Among("\u0161ena", 19, 7, "", methodObject),
		new Among("\u017Eena", 19, 13, "", methodObject),
		new Among("skna", 18, 9, "", methodObject),
		new Among("\u00E1na", 18, 12, "", methodObject),
		new Among("r\u00E1na", 26, 2, "", methodObject),
		new Among("ov\u00E1na", 26, 1, "", methodObject),
		new Among("z\u00E1na", 26, 4, "", methodObject),
		new Among("\u011Bna", 18, 10, "", methodObject),
		new Among("st\u011Bna", 30, 14, "", methodObject),
		new Among("\u0161t\u011Bna", 30, 16, "", methodObject),
		new Among("ra", 0, 11, "", methodObject),
		new Among("era", 33, 2, "", methodObject),
		new Among("ta", 0, 3, "", methodObject),
		new Among("ata", 35, 5, "", methodObject),
		new Among("nuta", 35, 5, "", methodObject),
		new Among("sknuta", 37, 9, "", methodObject),
		new Among("ouc", -1, 3, "", methodObject),
		new Among("kouc", 39, 6, "", methodObject),
		new Among("nouc", 39, 5, "", methodObject),
		new Among("sknouc", 41, 9, "", methodObject),
		new Among("rouc", 39, 11, "", methodObject),
		new Among("erouc", 43, 2, "", methodObject),
		new Among("\u00EDc", -1, 16, "", methodObject),
		new Among("d\u00EDc", 45, 15, "", methodObject),
		new Among("j\u00EDc", 45, 3, "", methodObject),
		new Among("aj\u00EDc", 47, 12, "", methodObject),
		new Among("ej\u00EDc", 47, 8, "", methodObject),
		new Among("uj\u00EDc", 47, 1, "", methodObject),
		new Among("s\u00EDc", 45, 7, "", methodObject),
		new Among("st\u00EDc", 45, 14, "", methodObject),
		new Among("z\u00EDc", 45, 13, "", methodObject),
		new Among("\u017E\u00EDc", 45, 4, "", methodObject),
		new Among("ouce", -1, 3, "", methodObject),
		new Among("kouce", 55, 6, "", methodObject),
		new Among("nouce", 55, 5, "", methodObject),
		new Among("sknouce", 57, 9, "", methodObject),
		new Among("rouce", 55, 11, "", methodObject),
		new Among("erouce", 59, 2, "", methodObject),
		new Among("\u00EDce", -1, 16, "", methodObject),
		new Among("d\u00EDce", 61, 15, "", methodObject),
		new Among("j\u00EDce", 61, 3, "", methodObject),
		new Among("aj\u00EDce", 63, 12, "", methodObject),
		new Among("ej\u00EDce", 63, 8, "", methodObject),
		new Among("uj\u00EDce", 63, 1, "", methodObject),
		new Among("s\u00EDce", 61, 7, "", methodObject),
		new Among("st\u00EDce", 61, 14, "", methodObject),
		new Among("z\u00EDce", 61, 13, "", methodObject),
		new Among("\u017E\u00EDce", 61, 4, "", methodObject),
		new Among("je", -1, 3, "", methodObject),
		new Among("aje", 71, 12, "", methodObject),
		new Among("eje", 71, 8, "", methodObject),
		new Among("uje", 71, 1, "", methodObject),
		new Among("me", -1, 16, "", methodObject),
		new Among("eme", 75, 3, "", methodObject),
		new Among("jeme", 76, 3, "", methodObject),
		new Among("ujeme", 77, 1, "", methodObject),
		new Among("neme", 76, 5, "", methodObject),
		new Among("skneme", 79, 9, "", methodObject),
		new Among("ereme", 76, 2, "", methodObject),
		new Among("\u010Deme", 76, 6, "", methodObject),
		new Among("\u0159eme", 76, 11, "", methodObject),
		new Among("\u017Eeme", 76, 4, "", methodObject),
		new Among("jme", 75, 3, "", methodObject),
		new Among("ejme", 85, 16, "", methodObject),
		new Among("ujme", 85, 1, "", methodObject),
		new Among("erme", 75, 2, "", methodObject),
		new Among("sme", 75, 7, "", methodObject),
		new Among("zme", 75, 13, "", methodObject),
		new Among("\u00E1me", 75, 12, "", methodObject),
		new Among("\u00EDme", 75, 16, "", methodObject),
		new Among("d\u00EDme", 92, 15, "", methodObject),
		new Among("s\u00EDme", 92, 7, "", methodObject),
		new Among("st\u00EDme", 92, 14, "", methodObject),
		new Among("z\u00EDme", 92, 13, "", methodObject),
		new Among("\u010Dme", 75, 6, "", methodObject),
		new Among("\u010Fme", 75, 15, "", methodObject),
		new Among("n\u011Bme", 75, 5, "", methodObject),
		new Among("skn\u011Bme", 99, 9, "", methodObject),
		new Among("st\u011Bme", 75, 14, "", methodObject),
		new Among("\u0148me", 75, 5, "", methodObject),
		new Among("\u017Eme", 75, 4, "", methodObject),
		new Among("ne", -1, 5, "", methodObject),
		new Among("skne", 104, 9, "", methodObject),
		new Among("ere", -1, 2, "", methodObject),
		new Among("se", -1, 7, "", methodObject),
		new Among("te", -1, 16, "", methodObject),
		new Among("ete", 108, 3, "", methodObject),
		new Among("jete", 109, 3, "", methodObject),
		new Among("ujete", 110, 1, "", methodObject),
		new Among("nete", 109, 5, "", methodObject),
		new Among("sknete", 112, 9, "", methodObject),
		new Among("erete", 109, 2, "", methodObject),
		new Among("\u010Dete", 109, 6, "", methodObject),
		new Among("\u0159ete", 109, 11, "", methodObject),
		new Among("\u017Eete", 109, 4, "", methodObject),
		new Among("jte", 108, 3, "", methodObject),
		new Among("ejte", 118, 16, "", methodObject),
		new Among("ujte", 118, 1, "", methodObject),
		new Among("erte", 108, 2, "", methodObject),
		new Among("ste", 108, 7, "", methodObject),
		new Among("zte", 108, 13, "", methodObject),
		new Among("\u00E1te", 108, 12, "", methodObject),
		new Among("\u00EDte", 108, 16, "", methodObject),
		new Among("d\u00EDte", 125, 15, "", methodObject),
		new Among("s\u00EDte", 125, 7, "", methodObject),
		new Among("st\u00EDte", 125, 14, "", methodObject),
		new Among("z\u00EDte", 125, 13, "", methodObject),
		new Among("\u010Dte", 108, 6, "", methodObject),
		new Among("\u010Fte", 108, 15, "", methodObject),
		new Among("n\u011Bte", 108, 5, "", methodObject),
		new Among("skn\u011Bte", 132, 9, "", methodObject),
		new Among("st\u011Bte", 108, 14, "", methodObject),
		new Among("\u0148te", 108, 5, "", methodObject),
		new Among("\u017Ete", 108, 4, "", methodObject),
		new Among("ze", -1, 13, "", methodObject),
		new Among("\u010De", -1, 6, "", methodObject),
		new Among("\u0159e", -1, 11, "", methodObject),
		new Among("av\u0161e", -1, 5, "", methodObject),
		new Among("nuv\u0161e", -1, 5, "", methodObject),
		new Among("\u017Ee", -1, 4, "", methodObject),
		new Among("ji", -1, 3, "", methodObject),
		new Among("uji", 143, 1, "", methodObject),
		new Among("li", -1, 3, "", methodObject),
		new Among("ali", 145, 16, "", methodObject),
		new Among("rali", 146, 2, "", methodObject),
		new Among("ovali", 146, 1, "", methodObject),
		new Among("zali", 146, 4, "", methodObject),
		new Among("eli", 145, 8, "", methodObject),
		new Among("\u0159eli", 150, 11, "", methodObject),
		new Among("ili", 145, 13, "", methodObject),
		new Among("dili", 152, 15, "", methodObject),
		new Among("sili", 152, 7, "", methodObject),
		new Among("stili", 152, 14, "", methodObject),
		new Among("zili", 152, 13, "", methodObject),
		new Among("kli", 145, 6, "", methodObject),
		new Among("skli", 157, 9, "", methodObject),
		new Among("nuli", 145, 5, "", methodObject),
		new Among("\u011Bli", 145, 10, "", methodObject),
		new Among("ni", -1, 5, "", methodObject),
		new Among("eni", 161, 16, "", methodObject),
		new Among("zeni", 162, 15, "", methodObject),
		new Among("\u010Deni", 162, 6, "", methodObject),
		new Among("\u0159eni", 162, 11, "", methodObject),
		new Among("\u0161eni", 162, 7, "", methodObject),
		new Among("\u017Eeni", 162, 13, "", methodObject),
		new Among("skni", 161, 9, "", methodObject),
		new Among("\u00E1ni", 161, 12, "", methodObject),
		new Among("r\u00E1ni", 169, 2, "", methodObject),
		new Among("ov\u00E1ni", 169, 1, "", methodObject),
		new Among("z\u00E1ni", 169, 4, "", methodObject),
		new Among("\u011Bni", 161, 10, "", methodObject),
		new Among("st\u011Bni", 173, 14, "", methodObject),
		new Among("\u0161t\u011Bni", 173, 16, "", methodObject),
		new Among("ti", -1, 3, "", methodObject),
		new Among("ati", 176, 5, "", methodObject),
		new Among("sti", 176, 14, "", methodObject),
		new Among("nuti", 176, 5, "", methodObject),
		new Among("sknuti", 179, 9, "", methodObject),
		new Among("\u0159i", -1, 11, "", methodObject),
		new Among("av\u0161i", -1, 5, "", methodObject),
		new Among("nuv\u0161i", -1, 5, "", methodObject),
		new Among("j", -1, 3, "", methodObject),
		new Among("ej", 184, 16, "", methodObject),
		new Among("uj", 184, 1, "", methodObject),
		new Among("l", -1, 3, "", methodObject),
		new Among("al", 187, 16, "", methodObject),
		new Among("ral", 188, 2, "", methodObject),
		new Among("oval", 188, 1, "", methodObject),
		new Among("zal", 188, 4, "", methodObject),
		new Among("el", 187, 8, "", methodObject),
		new Among("\u0159el", 192, 11, "", methodObject),
		new Among("il", 187, 13, "", methodObject),
		new Among("dil", 194, 15, "", methodObject),
		new Among("sil", 194, 7, "", methodObject),
		new Among("stil", 194, 14, "", methodObject),
		new Among("zil", 194, 13, "", methodObject),
		new Among("kl", 187, 6, "", methodObject),
		new Among("skl", 199, 9, "", methodObject),
		new Among("nul", 187, 5, "", methodObject),
		new Among("\u011Bl", 187, 10, "", methodObject),
		new Among("\u00E1m", -1, 12, "", methodObject),
		new Among("\u00EDm", -1, 16, "", methodObject),
		new Among("d\u00EDm", 204, 15, "", methodObject),
		new Among("s\u00EDm", 204, 7, "", methodObject),
		new Among("st\u00EDm", 204, 14, "", methodObject),
		new Among("z\u00EDm", 204, 13, "", methodObject),
		new Among("en", -1, 16, "", methodObject),
		new Among("zen", 209, 15, "", methodObject),
		new Among("\u010Den", 209, 6, "", methodObject),
		new Among("\u0159en", 209, 11, "", methodObject),
		new Among("\u0161en", 209, 7, "", methodObject),
		new Among("\u017Een", 209, 13, "", methodObject),
		new Among("\u00E1n", -1, 12, "", methodObject),
		new Among("r\u00E1n", 215, 2, "", methodObject),
		new Among("ov\u00E1n", 215, 1, "", methodObject),
		new Among("z\u00E1n", 215, 4, "", methodObject),
		new Among("\u011Bn", -1, 10, "", methodObject),
		new Among("st\u011Bn", 219, 14, "", methodObject),
		new Among("\u0161t\u011Bn", 219, 16, "", methodObject),
		new Among("lo", -1, 3, "", methodObject),
		new Among("alo", 222, 16, "", methodObject),
		new Among("ralo", 223, 2, "", methodObject),
		new Among("ovalo", 223, 1, "", methodObject),
		new Among("zalo", 223, 4, "", methodObject),
		new Among("elo", 222, 8, "", methodObject),
		new Among("\u0159elo", 227, 11, "", methodObject),
		new Among("ilo", 222, 13, "", methodObject),
		new Among("dilo", 229, 15, "", methodObject),
		new Among("silo", 229, 7, "", methodObject),
		new Among("stilo", 229, 14, "", methodObject),
		new Among("zilo", 229, 13, "", methodObject),
		new Among("klo", 222, 6, "", methodObject),
		new Among("sklo", 234, 9, "", methodObject),
		new Among("nulo", 222, 5, "", methodObject),
		new Among("\u011Blo", 222, 10, "", methodObject),
		new Among("eno", -1, 16, "", methodObject),
		new Among("zeno", 238, 15, "", methodObject),
		new Among("\u010Deno", 238, 6, "", methodObject),
		new Among("\u0159eno", 238, 11, "", methodObject),
		new Among("\u0161eno", 238, 7, "", methodObject),
		new Among("\u017Eeno", 238, 13, "", methodObject),
		new Among("\u00E1no", -1, 12, "", methodObject),
		new Among("r\u00E1no", 244, 2, "", methodObject),
		new Among("ov\u00E1no", 244, 1, "", methodObject),
		new Among("z\u00E1no", 244, 4, "", methodObject),
		new Among("\u011Bno", -1, 10, "", methodObject),
		new Among("st\u011Bno", 248, 14, "", methodObject),
		new Among("\u0161t\u011Bno", 248, 16, "", methodObject),
		new Among("to", -1, 3, "", methodObject),
		new Among("ato", 251, 5, "", methodObject),
		new Among("nuto", 251, 5, "", methodObject),
		new Among("sknuto", 253, 9, "", methodObject),
		new Among("er", -1, 2, "", methodObject),
		new Among("s", -1, 7, "", methodObject),
		new Among("at", -1, 5, "", methodObject),
		new Among("nut", -1, 5, "", methodObject),
		new Among("sknut", 258, 9, "", methodObject),
		new Among("u", -1, 3, "", methodObject),
		new Among("ju", 260, 3, "", methodObject),
		new Among("uju", 261, 1, "", methodObject),
		new Among("nu", 260, 5, "", methodObject),
		new Among("sknu", 263, 9, "", methodObject),
		new Among("ou", 260, 3, "", methodObject),
		new Among("jou", 265, 3, "", methodObject),
		new Among("ujou", 266, 1, "", methodObject),
		new Among("nou", 265, 5, "", methodObject),
		new Among("sknou", 268, 9, "", methodObject),
		new Among("erou", 265, 2, "", methodObject),
		new Among("\u010Dou", 265, 6, "", methodObject),
		new Among("\u0159ou", 265, 11, "", methodObject),
		new Among("\u017Eou", 265, 4, "", methodObject),
		new Among("eru", 260, 2, "", methodObject),
		new Among("\u010Du", 260, 6, "", methodObject),
		new Among("\u0159u", 260, 11, "", methodObject),
		new Among("\u017Eu", 260, 4, "", methodObject),
		new Among("av", -1, 5, "", methodObject),
		new Among("nuv", -1, 5, "", methodObject),
		new Among("ly", -1, 3, "", methodObject),
		new Among("aly", 280, 16, "", methodObject),
		new Among("raly", 281, 2, "", methodObject),
		new Among("ovaly", 281, 1, "", methodObject),
		new Among("zaly", 281, 4, "", methodObject),
		new Among("ely", 280, 8, "", methodObject),
		new Among("\u0159ely", 285, 11, "", methodObject),
		new Among("ily", 280, 13, "", methodObject),
		new Among("dily", 287, 15, "", methodObject),
		new Among("sily", 287, 7, "", methodObject),
		new Among("stily", 287, 14, "", methodObject),
		new Among("zily", 287, 13, "", methodObject),
		new Among("kly", 280, 6, "", methodObject),
		new Among("skly", 292, 9, "", methodObject),
		new Among("nuly", 280, 5, "", methodObject),
		new Among("\u011Bly", 280, 10, "", methodObject),
		new Among("eny", -1, 16, "", methodObject),
		new Among("zeny", 296, 15, "", methodObject),
		new Among("\u010Deny", 296, 6, "", methodObject),
		new Among("\u0159eny", 296, 11, "", methodObject),
		new Among("\u0161eny", 296, 7, "", methodObject),
		new Among("\u017Eeny", 296, 13, "", methodObject),
		new Among("\u00E1ny", -1, 12, "", methodObject),
		new Among("r\u00E1ny", 302, 2, "", methodObject),
		new Among("ov\u00E1ny", 302, 1, "", methodObject),
		new Among("z\u00E1ny", 302, 4, "", methodObject),
		new Among("\u011Bny", -1, 10, "", methodObject),
		new Among("st\u011Bny", 306, 14, "", methodObject),
		new Among("\u0161t\u011Bny", 306, 16, "", methodObject),
		new Among("ty", -1, 3, "", methodObject),
		new Among("aty", 309, 5, "", methodObject),
		new Among("nuty", 309, 5, "", methodObject),
		new Among("sknuty", 311, 9, "", methodObject),
		new Among("z", -1, 13, "", methodObject),
		new Among("\u00E1", -1, 12, "", methodObject),
		new Among("d\u00ED", -1, 15, "", methodObject),
		new Among("j\u00ED", -1, 3, "", methodObject),
		new Among("aj\u00ED", 316, 12, "", methodObject),
		new Among("ej\u00ED", 316, 8, "", methodObject),
		new Among("uj\u00ED", 316, 1, "", methodObject),
		new Among("s\u00ED", -1, 7, "", methodObject),
		new Among("st\u00ED", -1, 14, "", methodObject),
		new Among("z\u00ED", -1, 13, "", methodObject),
		new Among("\u010D", -1, 6, "", methodObject),
		new Among("\u010F", -1, 15, "", methodObject),
		new Among("\u011B", -1, 10, "", methodObject),
		new Among("d\u011B", 325, 15, "", methodObject),
		new Among("st\u011B", 325, 14, "", methodObject),
		new Among("\u0148", -1, 5, "", methodObject),
		new Among("e\u0161", -1, 3, "", methodObject),
		new Among("je\u0161", 329, 3, "", methodObject),
		new Among("uje\u0161", 330, 1, "", methodObject),
		new Among("ne\u0161", 329, 5, "", methodObject),
		new Among("skne\u0161", 332, 9, "", methodObject),
		new Among("ere\u0161", 329, 2, "", methodObject),
		new Among("\u010De\u0161", 329, 6, "", methodObject),
		new Among("\u0159e\u0161", 329, 11, "", methodObject),
		new Among("\u017Ee\u0161", 329, 4, "", methodObject),
		new Among("\u00E1\u0161", -1, 12, "", methodObject),
		new Among("\u00ED\u0161", -1, 16, "", methodObject),
		new Among("d\u00ED\u0161", 339, 15, "", methodObject),
		new Among("s\u00ED\u0161", 339, 7, "", methodObject),
		new Among("st\u00ED\u0161", 339, 14, "", methodObject),
		new Among("z\u00ED\u0161", 339, 13, "", methodObject),
		new Among("\u017E", -1, 4, "", methodObject)
	};
	private final static Among a_8[] = {
		new Among("hle", -1, 1, "", methodObject),
		new Among("koli", -1, 1, "", methodObject),
		new Among("si", -1, 1, "", methodObject),
		new Among("mo", -1, 1, "", methodObject),
		new Among("koliv", -1, 1, "", methodObject),
		new Among("ky", -1, 1, "", methodObject)
	};
	private final static Among a_9[] = {
		new Among("bb", -1, 1, "", methodObject),
		new Among("dd", -1, 1, "", methodObject),
		new Among("ff", -1, 1, "", methodObject),
		new Among("gg", -1, 1, "", methodObject),
		new Among("mm", -1, 1, "", methodObject),
		new Among("nn", -1, 1, "", methodObject),
		new Among("pp", -1, 1, "", methodObject),
		new Among("rr", -1, 1, "", methodObject),
		new Among("tt", -1, 1, "", methodObject)
	};
	private static final char g_vowel[] = {17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 4, 18, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64};
	private static final char g_consonant[] = {119, 223, 119, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 64, 0, 128, 128, 8, 0, 0, 16};
	private static final char g_aeiou[] = {17, 65, 16};
	private boolean B_found_suffix;
	private int I_p1;

	private void copy_from(CzechStemmer other) {
		B_found_suffix = other.B_found_suffix;
		I_p1 = other.I_p1;
		super.copy_from(other);
	}

	private boolean r_mark_regions() {
		// (, line 47
		I_p1 = limit;
		// gopast, line 49
		golab0:
		while (true) {
			lab1:
			do {
				if (!(in_grouping(g_vowel, 97, 367))) {
					break lab1;
				}
				break golab0;
			} while (false);
			if (cursor >= limit) {
				return false;
			}
			cursor++;
		}
		// gopast, line 49
		golab2:
		while (true) {
			lab3:
			do {
				if (!(out_grouping(g_vowel, 97, 367))) {
					break lab3;
				}
				break golab2;
			} while (false);
			if (cursor >= limit) {
				return false;
			}
			cursor++;
		}
		// setmark p1, line 49
		I_p1 = cursor;
		return true;
	}

	private boolean r_postlude() {
		int among_var;
		int v_1;
		// repeat, line 52
		replab0:
		while (true) {
			v_1 = cursor;
			lab1:
			do {
				// (, line 52
				// [, line 53
				bra = cursor;
				// substring, line 53
				among_var = find_among(a_0, 16);
				if (among_var == 0) {
					break lab1;
				}
				// ], line 53
				ket = cursor;
				switch (among_var) {
					case 0:
						break lab1;
					case 1:
						// (, line 54
						// <-, line 54
						slice_from("a");
						break;
					case 2:
						// (, line 55
						// <-, line 55
						slice_from("e");
						break;
					case 3:
						// (, line 56
						// <-, line 56
						slice_from("i");
						break;
					case 4:
						// (, line 57
						// <-, line 57
						slice_from("o");
						break;
					case 5:
						// (, line 58
						// <-, line 58
						slice_from("u");
						break;
					case 6:
						// (, line 59
						// <-, line 59
						slice_from("y");
						break;
					case 7:
						// (, line 60
						// <-, line 60
						slice_from("c");
						break;
					case 8:
						// (, line 61
						// <-, line 61
						slice_from("d");
						break;
					case 9:
						// (, line 62
						// <-, line 62
						slice_from("e");
						break;
					case 10:
						// (, line 63
						// <-, line 63
						slice_from("n");
						break;
					case 11:
						// (, line 64
						// <-, line 64
						slice_from("r");
						break;
					case 12:
						// (, line 65
						// <-, line 65
						slice_from("s");
						break;
					case 13:
						// (, line 66
						// <-, line 66
						slice_from("t");
						break;
					case 14:
						// (, line 67
						// <-, line 67
						slice_from("u");
						break;
					case 15:
						// (, line 68
						// <-, line 68
						slice_from("z");
						break;
					case 16:
						// (, line 69
						// next, line 69
						if (cursor >= limit) {
							break lab1;
						}
						cursor++;
						break;
				}
				continue replab0;
			} while (false);
			cursor = v_1;
			break replab0;
		}
		return true;
	}

	private boolean r_exception() {
		int among_var;
		// (, line 73
		// [, line 74
		bra = cursor;
		// substring, line 74
		among_var = find_among(a_1, 125);
		if (among_var == 0) {
			return false;
		}
		// ], line 74
		ket = cursor;
		// atlimit, line 74
		if (cursor < limit) {
			return false;
		}
		switch (among_var) {
			case 0:
				return false;
			case 1:
				// (, line 79
				// <-, line 79
				slice_from("byt");
				break;
			case 2:
				// (, line 83
				// <-, line 83
				slice_from("mit");
				break;
			case 3:
				// (, line 89
				// <-, line 89
				slice_from("jit");
				break;
			case 4:
				// (, line 93
				// <-, line 93
				slice_from("jist");
				break;
			case 5:
				// (, line 97
				// <-, line 97
				slice_from("snist");
				break;
			case 6:
				// (, line 101
				// <-, line 101
				slice_from("videt");
				break;
			case 7:
				// (, line 106
				// <-, line 106
				slice_from("vedet");
				break;
			case 8:
				// (, line 111
				// <-, line 111
				slice_from("chtit");
				break;
		}
		return true;
	}

	private boolean r_R1() {
		if (!(I_p1 <= cursor)) {
			return false;
		}
		return true;
	}

	private boolean r_nouns_suffixes() {
		int among_var;
		int v_1;
		// (, line 118
		// do, line 119
		v_1 = limit - cursor;
		lab0:
		do {
			// (, line 119
			// [, line 120
			ket = cursor;
			// substring, line 120
			among_var = find_among_b(a_2, 170);
			if (among_var == 0) {
				break lab0;
			}
			// ], line 120
			bra = cursor;
			// call R1, line 120
			if (!r_R1()) {
				break lab0;
			}
			switch (among_var) {
				case 0:
					break lab0;
				case 1:
					// (, line 124
					// delete, line 125
					slice_del();
					// set found_suffix, line 127
					B_found_suffix = true;
					break;
				case 2:
					// (, line 130
					// delete, line 131
					slice_del();
					// (, line 132
					// [, line 132
					ket = cursor;
					// literal, line 132
					if (!(eq_s_b(1, "\u0161"))) {
						break lab0;
					}
					// ], line 132
					bra = cursor;
					// <-, line 132
					slice_from("ch");
					// set found_suffix, line 133
					B_found_suffix = true;
					break;
				case 3:
					// (, line 154
					// delete, line 155
					slice_del();
					// set found_suffix, line 156
					B_found_suffix = true;
					break;
			}
		} while (false);
		cursor = limit - v_1;
		return true;
	}

	private boolean r_nouns_endings() {
		int among_var;
		int v_1;
		int v_2;
		int v_3;
		int v_4;
		// (, line 164
		// do, line 165
		v_1 = limit - cursor;
		lab0:
		do {
			// (, line 165
			// [, line 166
			ket = cursor;
			// substring, line 166
			among_var = find_among_b(a_3, 136);
			if (among_var == 0) {
				break lab0;
			}
			// ], line 166
			bra = cursor;
			// call R1, line 166
			if (!r_R1()) {
				break lab0;
			}
			switch (among_var) {
				case 0:
					break lab0;
				case 1:
					// (, line 168
					// delete, line 169
					slice_del(); // <+, line 170
				{
					int c = cursor;
					insert(cursor, cursor, "ba");
					cursor = c;
				}
				break;
				case 2:
					// (, line 173
					// delete, line 174
					slice_del(); // <+, line 175
				{
					int c = cursor;
					insert(cursor, cursor, "ec");
					cursor = c;
				}
				break;
				case 3:
					// (, line 178
					// delete, line 179
					slice_del(); // <+, line 180
				{
					int c = cursor;
					insert(cursor, cursor, "lo");
					cursor = c;
				}
				break;
				case 4:
					// (, line 183
					// delete, line 184
					slice_del(); // <+, line 185
				{
					int c = cursor;
					insert(cursor, cursor, "ra");
					cursor = c;
				}
				break;
				case 5:
					// (, line 188
					// delete, line 189
					slice_del(); // <+, line 190
				{
					int c = cursor;
					insert(cursor, cursor, "na");
					cursor = c;
				}
				break;
				case 6:
					// (, line 193
					// delete, line 194
					slice_del(); // <+, line 195
				{
					int c = cursor;
					insert(cursor, cursor, "e");
					cursor = c;
				}
				break;
				case 7:
					// (, line 198
					// delete, line 199
					slice_del(); // <+, line 200
				{
					int c = cursor;
					insert(cursor, cursor, "no");
					cursor = c;
				}
				break;
				case 8:
					// (, line 203
					// delete, line 204
					slice_del(); // <+, line 205
				{
					int c = cursor;
					insert(cursor, cursor, "va");
					cursor = c;
				}
				break;
				case 9:
					// (, line 208
					// delete, line 209
					slice_del(); // <+, line 210
				{
					int c = cursor;
					insert(cursor, cursor, "ek");
					cursor = c;
				}
				break;
				case 10:
					// (, line 213
					// delete, line 214
					slice_del(); // <+, line 215
				{
					int c = cursor;
					insert(cursor, cursor, "t\u011B");
					cursor = c;
				}
				break;
				case 11:
					// (, line 218
					// delete, line 219
					slice_del(); // <+, line 220
				{
					int c = cursor;
					insert(cursor, cursor, "g");
					cursor = c;
				}
				break;
				case 12:
					// (, line 223
					// delete, line 224
					slice_del(); // <+, line 225
				{
					int c = cursor;
					insert(cursor, cursor, "vo");
					cursor = c;
				}
				break;
				case 13:
					// (, line 228
					// delete, line 229
					slice_del(); // <+, line 230
				{
					int c = cursor;
					insert(cursor, cursor, "a");
					cursor = c;
				}
				break;
				case 14:
					// (, line 233
					// delete, line 234
					slice_del();
					// test, line 235
					v_2 = limit - cursor;
					if (!(in_grouping_b(g_aeiou, 97, 117))) {
						break lab0;
					}
					cursor = limit - v_2; // (, line 235
				// <+, line 235
				{
					int c = cursor;
					insert(cursor, cursor, "\u0148");
					cursor = c;
				}
				// test, line 236
				v_3 = limit - cursor;
				// literal, line 236
				if (!(eq_s_b(1, "y"))) {
					break lab0;
				}
				cursor = limit - v_3; // (, line 236
				// <+, line 236
				{
					int c = cursor;
					insert(cursor, cursor, "n\u011B");
					cursor = c;
				}
				// test, line 237
				v_4 = limit - cursor;
				if (!(in_grouping_b(g_consonant, 98, 382))) {
					break lab0;
				}
				cursor = limit - v_4; // (, line 237
				// <+, line 237
				{
					int c = cursor;
					insert(cursor, cursor, "e\u0148");
					cursor = c;
				}
				// set found_suffix, line 238
				B_found_suffix = true;
				break;
				case 15:
					// (, line 241
					// delete, line 242
					slice_del(); // <+, line 243
				{
					int c = cursor;
					insert(cursor, cursor, "\u011B");
					cursor = c;
				}
				break;
				case 16:
					// (, line 246
					// delete, line 247
					slice_del(); // <+, line 248
				{
					int c = cursor;
					insert(cursor, cursor, "ka");
					cursor = c;
				}
				break;
				case 17:
					// (, line 257
					// delete, line 258
					slice_del();
					break;
			}
		} while (false);
		cursor = limit - v_1;
		return true;
	}

	private boolean r_adjectives_suffixes() {
		int among_var;
		int v_1;
		int v_2;
		int v_3;
		int v_4;
		// (, line 264
		// do, line 265
		v_1 = limit - cursor;
		lab0:
		do {
			// (, line 265
			// [, line 266
			ket = cursor;
			// substring, line 266
			among_var = find_among_b(a_4, 77);
			if (among_var == 0) {
				break lab0;
			}
			// ], line 266
			bra = cursor;
			// call R1, line 266
			if (!r_R1()) {
				break lab0;
			}
			switch (among_var) {
				case 0:
					break lab0;
				case 1:
					// (, line 280
					// delete, line 281
					slice_del();
					// set found_suffix, line 282
					B_found_suffix = true;
					break;
				case 2:
					// (, line 285
					// delete, line 286
					slice_del();
					// call alternance_i, line 287
					if (!r_alternance_i()) {
						break lab0;
					}
					// set found_suffix, line 288
					B_found_suffix = true;
					break;
				case 3:
					// (, line 291
					// delete, line 292
					slice_del();
					// or, line 293
					lab1:
					do {
						v_2 = limit - cursor;
						lab2:
						do {
							// (, line 293
							// [, line 293
							ket = cursor;
							// literal, line 293
							if (!(eq_s_b(1, "\u017E"))) {
								break lab2;
							}
							// ], line 293
							bra = cursor;
							// <-, line 293
							slice_from("h");
							break lab1;
						} while (false);
						cursor = limit - v_2;
						// (, line 293
						// [, line 293
						ket = cursor;
						// literal, line 293
						if (!(eq_s_b(1, "\u0161"))) {
							break lab0;
						}
						// ], line 293
						bra = cursor;
						// <-, line 293
						slice_from("ch");
					} while (false);
					// set found_suffix, line 294
					B_found_suffix = true;
					break;
				case 4:
					// (, line 297
					// delete, line 298
					slice_del();
					// or, line 299
					lab3:
					do {
						v_3 = limit - cursor;
						lab4:
						do {
							// (, line 299
							// [, line 299
							ket = cursor;
							// literal, line 299
							if (!(eq_s_b(1, "\u017E"))) {
								break lab4;
							}
							// ], line 299
							bra = cursor;
							// <-, line 299
							slice_from("h");
							break lab3;
						} while (false);
						cursor = limit - v_3;
						lab5:
						do {
							// (, line 299
							// [, line 299
							ket = cursor;
							// literal, line 299
							if (!(eq_s_b(1, "\u0161"))) {
								break lab5;
							}
							// ], line 299
							bra = cursor;
							// <-, line 299
							slice_from("ch");
							break lab3;
						} while (false);
						cursor = limit - v_3;
						// (, line 299
						// [, line 299
						ket = cursor;
						// literal, line 299
						if (!(eq_s_b(1, "\u010D"))) {
							break lab0;
						}
						// ], line 299
						bra = cursor;
						// <-, line 299
						slice_from("k");
					} while (false);
					// set found_suffix, line 300
					B_found_suffix = true;
					break;
				case 5:
					// (, line 303
					// delete, line 304
					slice_del();
					// (, line 305
					// [, line 305
					ket = cursor;
					// literal, line 305
					if (!(eq_s_b(1, "\u010D"))) {
						break lab0;
					}
					// ], line 305
					bra = cursor;
					// <-, line 305
					slice_from("k");
					// set found_suffix, line 306
					B_found_suffix = true;
					break;
				case 6:
					// (, line 309
					// delete, line 310
					slice_del();
					// or, line 311
					lab6:
					do {
						v_4 = limit - cursor;
						lab7:
						do {
							// (, line 311
							// [, line 311
							ket = cursor;
							// literal, line 311
							if (!(eq_s_b(1, "\u010D"))) {
								break lab7;
							}
							// ], line 311
							bra = cursor;
							// <-, line 311
							slice_from("k");
							break lab6;
						} while (false);
						cursor = limit - v_4;
						lab8:
						do {
							// (, line 312
							// [, line 312
							ket = cursor;
							// literal, line 312
							if (!(eq_s_b(2, "\u010D\u0165"))) {
								break lab8;
							}
							// ], line 312
							bra = cursor;
							// <-, line 312
							slice_from("ck");
							break lab6;
						} while (false);
						cursor = limit - v_4;
						lab9:
						do {
							// (, line 313
							// [, line 313
							ket = cursor;
							// literal, line 313
							if (!(eq_s_b(2, "\u0161\u0165"))) {
								break lab9;
							}
							// ], line 313
							bra = cursor;
							// <-, line 313
							slice_from("sk");
							break lab6;
						} while (false);
						cursor = limit - v_4;
						lab10:
						do {
							// (, line 314
							// [, line 314
							ket = cursor;
							// literal, line 314
							if (!(eq_s_b(1, "\u017E"))) {
								break lab10;
							}
							// ], line 314
							bra = cursor;
							// <-, line 314
							slice_from("h");
							break lab6;
						} while (false);
						cursor = limit - v_4;
						// (, line 315
						// [, line 315
						ket = cursor;
						// literal, line 315
						if (!(eq_s_b(1, "\u0161"))) {
							break lab0;
						}
						// ], line 315
						bra = cursor;
						// <-, line 315
						slice_from("ch");
					} while (false);
					// set found_suffix, line 316
					B_found_suffix = true;
					break;
			}
		} while (false);
		cursor = limit - v_1;
		return true;
	}

	private boolean r_adjectives_endings() {
		int among_var;
		int v_1;
		// (, line 322
		// do, line 323
		v_1 = limit - cursor;
		lab0:
		do {
			// (, line 323
			// [, line 324
			ket = cursor;
			// substring, line 324
			among_var = find_among_b(a_5, 111);
			if (among_var == 0) {
				break lab0;
			}
			// ], line 324
			bra = cursor;
			// call R1, line 324
			if (!r_R1()) {
				break lab0;
			}
			switch (among_var) {
				case 0:
					break lab0;
				case 1:
					// (, line 327
					// delete, line 328
					slice_del(); // <+, line 329
				{
					int c = cursor;
					insert(cursor, cursor, "sk\u00FD");
					cursor = c;
				}
				break;
				case 2:
					// (, line 333
					// delete, line 334
					slice_del(); // <+, line 335
				{
					int c = cursor;
					insert(cursor, cursor, "ck\u00FD");
					cursor = c;
				}
				break;
				case 3:
					// (, line 339
					// delete, line 340
					slice_del(); // <+, line 341
				{
					int c = cursor;
					insert(cursor, cursor, "k\u00FD");
					cursor = c;
				}
				break;
				case 4:
					// (, line 346
					// delete, line 347
					slice_del(); // <+, line 348
				{
					int c = cursor;
					insert(cursor, cursor, "ch\u00FD");
					cursor = c;
				}
				break;
				case 5:
					// (, line 353
					// delete, line 354
					slice_del(); // <+, line 355
				{
					int c = cursor;
					insert(cursor, cursor, "h\u00FD");
					cursor = c;
				}
				break;
				case 6:
					// (, line 360
					// delete, line 361
					slice_del(); // <+, line 362
				{
					int c = cursor;
					insert(cursor, cursor, "r\u00FD");
					cursor = c;
				}
				break;
				case 7:
					// (, line 365
					// delete, line 366
					slice_del(); // <+, line 367
				{
					int c = cursor;
					insert(cursor, cursor, "av\u00FD");
					cursor = c;
				}
				break;
				case 8:
					// (, line 372
					// delete, line 373
					slice_del(); // <+, line 374
				{
					int c = cursor;
					insert(cursor, cursor, "\u00ED");
					cursor = c;
				}
				break;
				case 9:
					// (, line 379
					// delete, line 380
					slice_del(); // <+, line 381
				{
					int c = cursor;
					insert(cursor, cursor, "\u016Fv");
					cursor = c;
				}
				break;
				case 10:
					// (, line 385
					// delete, line 386
					slice_del(); // <+, line 387
				{
					int c = cursor;
					insert(cursor, cursor, "\u00FD");
					cursor = c;
				}
				break;
				case 11:
					// (, line 391
					// delete, line 392
					slice_del(); // <+, line 393
				{
					int c = cursor;
					insert(cursor, cursor, "in");
					cursor = c;
				}
				break;
				case 12:
					// (, line 396
					// delete, line 397
					slice_del(); // <+, line 398
				{
					int c = cursor;
					insert(cursor, cursor, "\u00FD");
					cursor = c;
				}
				break;
			}
		} while (false);
		cursor = limit - v_1;
		return true;
	}

	private boolean r_verbs_suffixes() {
		int among_var;
		int v_1;
		// (, line 404
		// do, line 405
		v_1 = limit - cursor;
		lab0:
		do {
			// (, line 405
			// [, line 406
			ket = cursor;
			// substring, line 406
			among_var = find_among_b(a_6, 15);
			if (among_var == 0) {
				break lab0;
			}
			// ], line 406
			bra = cursor;
			// call R1, line 406
			if (!r_R1()) {
				break lab0;
			}
			switch (among_var) {
				case 0:
					break lab0;
				case 1:
					// (, line 409
					// set found_suffix, line 411
					B_found_suffix = true;
					break;
			}
		} while (false);
		cursor = limit - v_1;
		return true;
	}

	private boolean r_verbs_endings() {
		int among_var;
		int v_1;
		// (, line 417
		// do, line 418
		v_1 = limit - cursor;
		lab0:
		do {
			// (, line 418
			// [, line 419
			ket = cursor;
			// substring, line 419
			among_var = find_among_b(a_7, 345);
			if (among_var == 0) {
				break lab0;
			}
			// ], line 419
			bra = cursor;
			switch (among_var) {
				case 0:
					break lab0;
				case 1:
					// (, line 424
					// delete, line 425
					slice_del(); // <+, line 426
				{
					int c = cursor;
					insert(cursor, cursor, "ovat");
					cursor = c;
				}
				break;
				case 2:
					// (, line 431
					// delete, line 432
					slice_del(); // <+, line 433
				{
					int c = cursor;
					insert(cursor, cursor, "r\u00E1t");
					cursor = c;
				}
				break;
				case 3:
					// (, line 438
					// delete, line 439
					slice_del(); // <+, line 440
				{
					int c = cursor;
					insert(cursor, cursor, "t");
					cursor = c;
				}
				break;
				case 4:
					// (, line 446
					// delete, line 447
					slice_del(); // <+, line 448
				{
					int c = cursor;
					insert(cursor, cursor, "zat");
					cursor = c;
				}
				break;
				case 5:
					// (, line 455
					// delete, line 456
					slice_del(); // <+, line 457
				{
					int c = cursor;
					insert(cursor, cursor, "nout");
					cursor = c;
				}
				break;
				case 6:
					// (, line 462
					// delete, line 463
					slice_del(); // <+, line 464
				{
					int c = cursor;
					insert(cursor, cursor, "ct");
					cursor = c;
				}
				break;
				case 7:
					// (, line 469
					// delete, line 470
					slice_del(); // <+, line 471
				{
					int c = cursor;
					insert(cursor, cursor, "sit");
					cursor = c;
				}
				break;
				case 8:
					// (, line 474
					// delete, line 475
					slice_del(); // <+, line 476
				{
					int c = cursor;
					insert(cursor, cursor, "et");
					cursor = c;
				}
				break;
				case 9:
					// (, line 481
					// delete, line 482
					slice_del(); // <+, line 483
				{
					int c = cursor;
					insert(cursor, cursor, "sknout");
					cursor = c;
				}
				break;
				case 10:
					// (, line 487
					// delete, line 488
					slice_del(); // <+, line 489
				{
					int c = cursor;
					insert(cursor, cursor, "\u011Bt");
					cursor = c;
				}
				break;
				case 11:
					// (, line 494
					// delete, line 495
					slice_del(); // <+, line 496
				{
					int c = cursor;
					insert(cursor, cursor, "\u0159\u00EDt");
					cursor = c;
				}
				break;
				case 12:
					// (, line 500
					// delete, line 501
					slice_del(); // <+, line 502
				{
					int c = cursor;
					insert(cursor, cursor, "at");
					cursor = c;
				}
				break;
				case 13:
					// (, line 508
					// delete, line 509
					slice_del(); // <+, line 510
				{
					int c = cursor;
					insert(cursor, cursor, "zit");
					cursor = c;
				}
				break;
				case 14:
					// (, line 516
					// delete, line 517
					slice_del(); // <+, line 518
				{
					int c = cursor;
					insert(cursor, cursor, "stit");
					cursor = c;
				}
				break;
				case 15:
					// (, line 523
					// delete, line 524
					slice_del(); // <+, line 525
				{
					int c = cursor;
					insert(cursor, cursor, "dit");
					cursor = c;
				}
				break;
				case 16:
					// (, line 532
					// delete, line 533
					slice_del();
					break;
			}
		} while (false);
		cursor = limit - v_1;
		return true;
	}

	private boolean r_adverbs_suffixes() {
		int among_var;
		int v_1;
		// (, line 539
		// do, line 540
		v_1 = limit - cursor;
		lab0:
		do {
			// (, line 540
			// [, line 541
			ket = cursor;
			// substring, line 541
			among_var = find_among_b(a_8, 6);
			if (among_var == 0) {
				break lab0;
			}
			// ], line 541
			bra = cursor;
			// call R1, line 541
			if (!r_R1()) {
				break lab0;
			}
			switch (among_var) {
				case 0:
					break lab0;
				case 1:
					// (, line 543
					// delete, line 544
					slice_del();
					// set found_suffix, line 545
					B_found_suffix = true;
					break;
			}
		} while (false);
		cursor = limit - v_1;
		return true;
	}

	private boolean r_end_vowel() {
		// (, line 551
		// [, line 552
		ket = cursor;
		if (!(in_grouping_b(g_vowel, 97, 367))) {
			return false;
		}
		// ], line 552
		bra = cursor;
		// <-, line 552
		slice_from("");
		// [, line 553
		ket = cursor;
		if (!(in_grouping_b(g_vowel, 97, 367))) {
			return false;
		}
		// ], line 553
		bra = cursor;
		// <-, line 553
		slice_from("");
		return true;
	}

	private boolean r_alternance_i() {
		int v_1;
		// (, line 556
		// or, line 557
		lab0:
		do {
			v_1 = limit - cursor;
			lab1:
			do {
				// (, line 557
				// [, line 557
				ket = cursor;
				// literal, line 557
				if (!(eq_s_b(1, "\u010D"))) {
					break lab1;
				}
				// ], line 557
				bra = cursor;
				// <-, line 557
				slice_from("k");
				break lab0;
			} while (false);
			cursor = limit - v_1;
			// (, line 557
			// [, line 557
			ket = cursor;
			// literal, line 557
			if (!(eq_s_b(1, "\u0161"))) {
				return false;
			}
			// ], line 557
			bra = cursor;
			// <-, line 557
			slice_from("ch");
		} while (false);
		return true;
	}

	private boolean r_end_double() {
		int among_var;
		int v_1;
		// (, line 560
		// test, line 561
		v_1 = limit - cursor;
		// substring, line 561
		among_var = find_among_b(a_9, 9);
		if (among_var == 0) {
			return false;
		}
		cursor = limit - v_1;
		switch (among_var) {
			case 0:
				return false;
			case 1:
				// (, line 563
				// [, line 563
				ket = cursor;
				// next, line 563
				if (cursor <= limit_backward) {
					return false;
				}
				cursor--;
				// ], line 563
				bra = cursor;
				// delete, line 563
				slice_del();
				break;
		}
		return true;
	}

	public boolean stem() {
		int v_1;
		int v_2;
		int v_3;
		int v_4;
		int v_5;
		int v_6;
		int v_7;
		int v_8;
		int v_9;
		int v_10;
		int v_11;
		int v_12;
		int v_13;
		int v_14;
		int v_15;
		int v_16;
		int v_17;
		int v_18;
		int v_19;
		int v_20;
		int v_21;
		int v_22;
		int v_23;
		// (, line 570
		// or, line 571
		lab0:
		do {
			v_1 = cursor;
			lab1:
			do {
				// call exception, line 571
				if (!r_exception()) {
					break lab1;
				}
				break lab0;
			} while (false);
			cursor = v_1;
			lab2:
			do {
				// not, line 572
				{
					v_2 = cursor;
					lab3:
					do {
						// hop, line 572
						{
							int c = cursor + 4;
							if (0 > c || c > limit) {
								break lab3;
							}
							cursor = c;
						}
						break lab2;
					} while (false);
					cursor = v_2;
				}
				break lab0;
			} while (false);
			cursor = v_1;
			// (, line 572
			// do, line 573
			v_3 = cursor;
			lab4:
			do {
				// call mark_regions, line 573
				if (!r_mark_regions()) {
					break lab4;
				}
			} while (false);
			cursor = v_3;
			// unset found_suffix, line 574
			B_found_suffix = false;
			// backwards, line 575
			limit_backward = cursor;
			cursor = limit;
			// (, line 575
			// do, line 576
			v_4 = limit - cursor;
			lab5:
			do {
				// call nouns_suffixes, line 576
				if (!r_nouns_suffixes()) {
					break lab5;
				}
			} while (false);
			cursor = limit - v_4;
			// or, line 577
			lab6:
			do {
				v_5 = limit - cursor;
				lab7:
				do {
					// Boolean test found_suffix, line 577
					if (!(B_found_suffix)) {
						break lab7;
					}
					break lab6;
				} while (false);
				cursor = limit - v_5;
				// do, line 577
				v_6 = limit - cursor;
				lab8:
				do {
					// call nouns_endings, line 577
					if (!r_nouns_endings()) {
						break lab8;
					}
				} while (false);
				cursor = limit - v_6;
			} while (false);
			// or, line 578
			lab9:
			do {
				v_7 = limit - cursor;
				lab10:
				do {
					// Boolean test found_suffix, line 578
					if (!(B_found_suffix)) {
						break lab10;
					}
					break lab9;
				} while (false);
				cursor = limit - v_7;
				// do, line 578
				v_8 = limit - cursor;
				lab11:
				do {
					// call nouns_suffixes, line 578
					if (!r_nouns_suffixes()) {
						break lab11;
					}
				} while (false);
				cursor = limit - v_8;
			} while (false);
			// or, line 580
			lab12:
			do {
				v_9 = limit - cursor;
				lab13:
				do {
					// Boolean test found_suffix, line 580
					if (!(B_found_suffix)) {
						break lab13;
					}
					break lab12;
				} while (false);
				cursor = limit - v_9;
				// do, line 580
				v_10 = limit - cursor;
				lab14:
				do {
					// call adjectives_suffixes, line 580
					if (!r_adjectives_suffixes()) {
						break lab14;
					}
				} while (false);
				cursor = limit - v_10;
			} while (false);
			// or, line 581
			lab15:
			do {
				v_11 = limit - cursor;
				lab16:
				do {
					// Boolean test found_suffix, line 581
					if (!(B_found_suffix)) {
						break lab16;
					}
					break lab15;
				} while (false);
				cursor = limit - v_11;
				// do, line 581
				v_12 = limit - cursor;
				lab17:
				do {
					// call adjectives_endings, line 581
					if (!r_adjectives_endings()) {
						break lab17;
					}
				} while (false);
				cursor = limit - v_12;
			} while (false);
			// or, line 582
			lab18:
			do {
				v_13 = limit - cursor;
				lab19:
				do {
					// Boolean test found_suffix, line 582
					if (!(B_found_suffix)) {
						break lab19;
					}
					break lab18;
				} while (false);
				cursor = limit - v_13;
				// do, line 582
				v_14 = limit - cursor;
				lab20:
				do {
					// call adjectives_suffixes, line 582
					if (!r_adjectives_suffixes()) {
						break lab20;
					}
				} while (false);
				cursor = limit - v_14;
			} while (false);
			// or, line 584
			lab21:
			do {
				v_15 = limit - cursor;
				lab22:
				do {
					// Boolean test found_suffix, line 584
					if (!(B_found_suffix)) {
						break lab22;
					}
					break lab21;
				} while (false);
				cursor = limit - v_15;
				// call adverbs_suffixes, line 584
				if (!r_adverbs_suffixes()) {
					return false;
				}
			} while (false);
			// or, line 587
			lab23:
			do {
				v_16 = limit - cursor;
				lab24:
				do {
					// Boolean test found_suffix, line 587
					if (!(B_found_suffix)) {
						break lab24;
					}
					break lab23;
				} while (false);
				cursor = limit - v_16;
				// do, line 587
				v_17 = limit - cursor;
				lab25:
				do {
					// call verbs_endings, line 587
					if (!r_verbs_endings()) {
						break lab25;
					}
				} while (false);
				cursor = limit - v_17;
			} while (false);
			// or, line 588
			lab26:
			do {
				v_18 = limit - cursor;
				lab27:
				do {
					// Boolean test found_suffix, line 588
					if (!(B_found_suffix)) {
						break lab27;
					}
					break lab26;
				} while (false);
				cursor = limit - v_18;
				// do, line 588
				v_19 = limit - cursor;
				lab28:
				do {
					// call verbs_suffixes, line 588
					if (!r_verbs_suffixes()) {
						break lab28;
					}
				} while (false);
				cursor = limit - v_19;
			} while (false);
			// do, line 590
			v_20 = limit - cursor;
			lab29:
			do {
				// call end_double, line 590
				if (!r_end_double()) {
					break lab29;
				}
			} while (false);
			cursor = limit - v_20;
			// do, line 591
			v_21 = limit - cursor;
			lab30:
			do {
				// call end_vowel, line 591
				if (!r_end_vowel()) {
					break lab30;
				}
			} while (false);
			cursor = limit - v_21;
			// do, line 592
			v_22 = limit - cursor;
			lab31:
			do {
				// call end_double, line 592
				if (!r_end_double()) {
					break lab31;
				}
			} while (false);
			cursor = limit - v_22;
			cursor = limit_backward;
		} while (false);
		// do, line 595
		v_23 = cursor;
		lab32:
		do {
			// call postlude, line 595
			if (!r_postlude()) {
				break lab32;
			}
		} while (false);
		cursor = v_23;
		return true;
	}

	public boolean equals(Object o) {
		return o instanceof CzechStemmer;
	}

	public int hashCode() {
		return CzechStemmer.class.getName().hashCode();
	}
}
